# Generated by Django 3.0.7 on 2020-06-23 07:22

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_auto_20200623_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_file',
            field=tinymce.models.HTMLField(),
        ),
    ]
