# Generated by Django 3.0.7 on 2020-06-23 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_traders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Traders',
            new_name='Trader',
        ),
    ]
