# Generated by Django 3.0.7 on 2020-06-23 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_auto_20200623_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trader',
            old_name='email',
            new_name='EMAIL',
        ),
    ]
