# Generated by Django 3.0.7 on 2020-06-23 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0007_auto_20200623_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trader',
            old_name='IDENTIFIER',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='trader',
            old_name='EMAIL',
            new_name='email',
        ),
    ]
